"""Shared structural typing for Streamlit session state containers."""

from __future__ import annotations

from collections.abc import Iterable
from typing import Any, Protocol

SessionKey = str | int


class SessionStateLike(Protocol):
    """Structural subset of Streamlit session state used by Graphik."""

    def __contains__(self, key: object) -> bool: ...
    def __getitem__(self, key: SessionKey) -> Any: ...
    def __setitem__(self, key: SessionKey, value: Any) -> None: ...
    def __delitem__(self, key: SessionKey) -> None: ...
    def get(self, key: SessionKey, default: Any = ...) -> Any: ...
    def pop(self, key: SessionKey, default: Any = ...) -> Any: ...
    def setdefault(self, key: SessionKey, default: Any) -> Any: ...
    def keys(self) -> Iterable[SessionKey]: ...
